### PR TITLE
fix: build on ubuntu-20.04 to ensure compatibility

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by ronaldtse** [comment]
I believe this will fix:
* https://github.com/metanorma/bipm-si-brochure/pull/277

**Comment by maxirmx** [comment]
@CAMOBAP @ronaldtse 
Seesking help ....   Why rake for metanorma  fails like in this run https://github.com/fontist/ffi-libarchive-binary/actions/runs/12444447089/job/34744929504  ?   Is it something related to libarchive ?

Thank you

**Comment by CAMOBAP** [comment]
@maxirmx to b on the same page in https://github.com/fontist/ffi-libarchive-binary/actions/runs/12444447089/job/34744929504 where exactly it fails? All jobs look green

**Review by CAMOBAP — APPROVED** [review]

**Comment by maxirmx** [comment]
> @maxirmx to b on the same page in https://github.com/fontist/ffi-libarchive-binary/actions/runs/12444447089/job/34744929504 where exactly it fails? All jobs look green

In "metanorma" jobs it fails on "bundle exec rake"
I set contineue-on-failure: true to be able test  container
Sorry for confusion

**Comment by maxirmx** [comment]
The same issue with other gems 
https://github.com/fontist/fontist/actions/runs/12446693626/job/34749370945?pr=390
so I assume it is not related to my changes

**Pull request merged**
