### PR TITLE
WIP: aarch64-linux

### LINKED ISSUE #12: Build arm64-linux version for arm64
Similar to https://github.com/metanorma/emf2svg-ruby/pull/16

### PR DESCRIPTION
**Pull request by alexeymorozov**
Closes #12

### CODE REVIEW

**Comment by alexeymorozov** [comment]
Before merging it should be tested with Alpine to avoid issues like in https://github.com/lutaml/expressir/issues/106.

**Comment by alexeymorozov** [comment]
It's compiled but lacks necessary dependencies to unarchive `xar`. I think openssl is required for this.

```
# x86_64
ldd /usr/local/bundle/gems/ffi-libarchive-binary-0.2.5-x86_64-linux/lib/ffi-libarchive-binary/libarchive.so
	linux-vdso.so.1 (0x00007ffd53106000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f18a317f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f18a3165000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f18a2fa0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f18a2f9a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f18a2f78000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f18a35c6000)

# aarch64
ldd /usr/local/bundle/gems/ffi-libarchive-binary-0.2.5-aarch64-linux/lib/ffi-libarchive-binary/libarchive.so
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000005501933000)
	/lib/ld-linux-aarch64.so.1 (0x0000005500000000)
```

**Comment by ronaldtse** [comment]
@alexeymorozov Alpine provides a libarchive package: https://pkgs.alpinelinux.org/package/edge/main/x86/libarchive

Perhaps have a look at how they compile it?

**Comment by maxirmx** [comment]
This is a major rework with three goals in mind:
- fix/implement robust cross compilation scripts to target _aarch64-linux-gnu_ and _arm64_apple_darwin_ for libarchive and previously bundled libraries (zlib, libexpat, libcrypto)
- open a possibility to create _x86_64/aarch64-linux-musl_  native gems
- integrate lzma(7z) support that allows to replace _seven_zip_ruby_ gem in _excavate_ and further drop _seven_zip_ruby_ support

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thank you @maxirmx !

**Pull request merged**
